apiVersion: ipam.kettle.io/v1alpha1
kind: Network
metadata:
  labels:
    app.kubernetes.io/name: kettle
    app.kubernetes.io/managed-by: kustomize
  name: network-sample
spec:
    cidr: "10.0.0.0/24"
    gateway: "10.0.0.1"
    vlan: 100
    excludeIPs:
      - "10.0.0.2"
      - "10.0.0.3"
    ipRange: "10.0.0.4-10.0.0.10"
