apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  annotations:
    networking.kettle.io/networks: "network-sample"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
